server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    at.ase.respond.categorization: 'debug'

spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'db'

custom:
  questionschema:
    path: "/data/question_schema.json"
    protocolSelectorQuestionId: 6
