server:
  port: 8082

logging:
  level:
    at.ase.respond.dispatcher: 'debug'

rabbit:
  backoff-policy:
    multiplier: 5
    init-interval: 500
    max-interval: 10000
  retry-policy:
    max-attempts: 15
  exchange: 'respond-exchange'
  routes:
    requests: 'respond-requests-route'
    incidents: 'respond-incidents-route'
    resources:
      status: 'respond-resources-status-route'
      location: 'respond-resources-location-route'
  queues:
    incidents: 'respond-incidents-queue'
    requests: 'respond-requests-queue'
    resources:
      status: 'respond-resources-status-queue'
      location: 'respond-resources-location-queue'

spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: 'manual'
    host: 'localhost'
    port: 5672
    username: 'user'
    password: 'passwd'
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'db'
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:oauth2.pub
          jws-algorithms:
            - RS256
          audiences:
            - 'at.ase.respond'
