server:
  port: 8082

spring:
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: 'user'
    password: 'passwd'
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'db'
