apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: 24ss-ase-pr-inso-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: 24ss-ase-pr-inso-02
data:
  loki.yml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    ingester:
      wal:
        enabled: true
        dir: /data/loki/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          replication_factor: 1
          kvstore:
            store: inmemory
        final_sleep: 0s
    compactor:
      working_directory: /data/loki/compactor
      shared_store: filesystem
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/index_cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      retention_period: 24h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: 24ss-ase-pr-inso-02
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loki
  template:
    metadata:
      labels:
        name: loki
    spec:
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-storage
        - name: config
          configMap:
            name: loki-config
      containers:
        - name: loki
          image: grafana/loki:2.9.8 # Use the appropriate version
          args:
            - -config.file=/etc/loki/loki.yml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-storage
              mountPath: /data/loki
            - name: config
              mountPath: /etc/loki
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: 24ss-ase-pr-inso-02
spec:
  ports:
    - port: 80
      targetPort: 3100
      protocol: TCP
      name: http
  selector:
    name: loki
  type: ClusterIP