apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-sidecar-config-map
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: "debug"
    positions:
      filename: /tmp/positions.yaml
    clients: # Specify target
      - url: http://loki:80/loki/api/v1/push
    scrape_configs:
      - job_name:  "respond-logs"
        static_configs:
          - targets:
              - localhost
            labels:
              app: "log-test"
              __path__: /var/log/respond.log