version: '3.8'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=passwd'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.025"
        limits:
          memory: 512M
          cpus: "0.4"
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.025"
        limits:
          memory: 512M
          cpus: "0.4"
  rabbit:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=passwd'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.025"
        limits:
          memory: 512M
          cpus: "0.4"
  incident-service:
    build: '../incident'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - rabbit
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=passwd'
      - 'SPRING_RABBITMQ_HOST=rabbit'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=user'
      - 'SPRING_RABBITMQ_PASSWORD=passwd'
      - 'RABBIT_EXCHANGE=respond-exchange'
      - 'RABBIT_ROUTES_INCIDENTS=respond-incidents-route'
      - 'RABBIT_QUEUES_INCIDENTS=respond-incidents-queue'
      - 'RABBIT_BACKOFF_POLICY_MULTIPLIER=10'
      - 'RABBIT_BACKOFF_POLICY_INIT_INTERVAL=500'
      - 'RABBIT_BACKOFF_POLICY_MAX_INTERVAL=10000'
      - 'RABBIT_RETRY_POLICY_MAX_ATTEMPTS=15'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.1"
        limits:
          memory: 512M
          cpus: "0.1"
  categorization-service:
    build: '../categorization'
    ports:
      - '8083:8083'
    depends_on:
      - mongo
    environment:
      - 'SPRING_DATA_MONGODB_DATABASE=db'
      - 'SPRING_DATA_MONGODB_HOST=mongo'
      - 'SPRING_DATA_MONGODB_PORT=27017'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.1"
        limits:
          memory: 512M
          cpus: "0.1"
  dispatcher-service:
    build: '../dispatcher'
    ports:
      - '8082:8082'
    depends_on:
      - mongo
      - rabbit
    environment:
      - 'SPRING_DATA_MONGODB_DATABASE=db'
      - 'SPRING_DATA_MONGODB_HOST=mongo'
      - 'SPRING_DATA_MONGODB_PORT=27017'
      - 'SPRING_RABBITMQ_HOST=rabbit'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=user'
      - 'SPRING_RABBITMQ_PASSWORD=passwd'
      - 'SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE=manual'
      - 'RABBIT_EXCHANGE=respond-exchange'
      - 'RABBIT_ROUTES_INCIDENTS=respond-incidents-route'
      - 'RABBIT_QUEUES_INCIDENTS=respond-incidents-queue'
      - 'RABBIT_ROUTES_RESOURCES=respond-resources-route'
      - 'RABBIT_QUEUES_RESOURCES=respond-resources-queue'
      - 'RABBIT_BACKOFF_POLICY_MULTIPLIER=10'
      - 'RABBIT_BACKOFF_POLICY_INIT_INTERVAL=500'
      - 'RABBIT_BACKOFF_POLICY_MAX_INTERVAL=10000'
      - 'RABBIT_RETRY_POLICY_MAX_ATTEMPTS=15'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.1"
        limits:
          memory: 512M
          cpus: "0.1"
  datafeeder:
    build: '../datafeeder'
    ports:
      - '8084:8084'
    depends_on:
      - rabbit
    environment:
      - 'SPRING_RABBITMQ_HOST=rabbit'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=user'
      - 'SPRING_RABBITMQ_PASSWORD=passwd'
      - 'SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE=manual'
      - 'RABBIT_EXCHANGE=respond-exchange'
      - 'RABBIT_ROUTES_INCIDENTS=respond-incidents-route'
      - 'RABBIT_ROUTES_RESOURCES_STATUS=respond-resources-status-route'
      - 'RABBIT_ROUTES_RESOURCES_LOCATION=respond-resources-location-route'
      - 'RABBIT_QUEUES_INCIDENTS=respond-datafeeder-incidents-queue'
      - 'RABBIT_BACKOFF_POLICY_MULTIPLIER=10'
      - 'RABBIT_BACKOFF_POLICY_INIT_INTERVAL=500'
      - 'RABBIT_BACKOFF_POLICY_MAX_INTERVAL=10000'
      - 'RABBIT_RETRY_POLICY_MAX_ATTEMPTS=15'
    deploy:
      resources:
        reservations:
          memory: 256M
          cpus: "0.1"
        limits:
          memory: 512M
          cpus: "0.1"
  dashboard:
    build: 
      context: '../dashboard'
      args:
        - BUILD_ENV=dev
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.1"
