auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory
    final_sleep: 0s
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
limits_config:
  retention_period: 24h