server:
  port: 8081

spring:
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: 'user'
    password: 'passwd'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db'
    username: 'user'
    password: 'passwd'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create