server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"
positions:
  filename: /tmp/positions.yaml
clients: # Specify target
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name:  "respond-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/respond.log